# Generated by Django 5.2.4 on 2025-07-02 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('qr_type', models.CharField(choices=[('text', 'Texto'), ('url', 'URL'), ('email', 'Email'), ('phone', 'Telefone'), ('sms', 'SMS'), ('wifi', 'WiFi'), ('vcard', 'vCard')], default='text', max_length=10, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Histórico de QR Code',
                'verbose_name_plural': 'Histórico de QR Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
