# Generated by Django 5.2.4 on 2025-07-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodehistory',
            name='expiration_type',
            field=models.CharField(choices=[('1h', '1 Hora'), ('1d', '1 Dia'), ('1w', '1 Semana'), ('1m', '1 Mês'), ('never', 'Nunca')], default='never', max_length=10, verbose_name='Tipo de Expiração'),
        ),
        migrations.AddField(
            model_name='qrcodehistory',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expira em'),
        ),
        migrations.AddField(
            model_name='qrcodehistory',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Arquivo PDF'),
        ),
        migrations.AlterField(
            model_name='qrcodehistory',
            name='qr_type',
            field=models.CharField(choices=[('text', 'Texto'), ('url', 'URL'), ('email', 'Email'), ('phone', 'Telefone'), ('sms', 'SMS'), ('wifi', 'WiFi'), ('vcard', 'vCard'), ('pdf', 'PDF')], default='text', max_length=10, verbose_name='Tipo'),
        ),
    ]
