# Generated by Django 5.2.4 on 2025-07-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_generator', '0002_qrcodehistory_expiration_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodehistory',
            name='expiration_type',
            field=models.CharField(choices=[('1h', '1 Hora'), ('1d', '1 Dia'), ('1w', '1 Semana'), ('1m', '1 Mês'), ('custom', 'Personalizado'), ('never', 'Nunca')], default='never', max_length=10, verbose_name='Tipo de Expiração'),
        ),
    ]
