# Generated by Django 5.2.4 on 2025-07-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_generator', '0002_pdffile'),
        ('qrcode_generator', '0003_alter_qrcodehistory_expiration_type'),
    ]

    operations = [
    ]
