# Generated by Django 5.2.4 on 2025-07-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_generator', '0004_merge_20250708_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodehistory',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='qrcodehistory',
            name='pdf_file',
        ),
        migrations.AlterField(
            model_name='qrcodehistory',
            name='expiration_type',
            field=models.CharField(choices=[('never', 'Nunca Expira')], default='never', max_length=10, verbose_name='Tipo de Expiração'),
        ),
        migrations.AlterField(
            model_name='qrcodehistory',
            name='qr_type',
            field=models.CharField(choices=[('text', 'Texto'), ('url', 'URL'), ('email', 'Email'), ('phone', 'Telefone'), ('sms', 'SMS'), ('wifi', 'WiFi'), ('vcard', 'vCard')], default='text', max_length=10, verbose_name='Tipo'),
        ),
    ]
