# Generated by Django 5.2.4 on 2025-07-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_generator', '0006_alter_qrcodehistory_qr_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodehistory',
            name='expiration_type',
        ),
    ]
