# Generated by Django 5.2.4 on 2025-07-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_generator', '0007_remove_qrcodehistory_expiration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodehistory',
            name='qr_code_image',
            field=models.TextField(blank=True, verbose_name='Imagem do QR Code (Base64)'),
        ),
    ]
