# Generated by Django 5.2.4 on 2025-07-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_generator', '0009_qrcodehistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodehistory',
            name='title',
            field=models.CharField(blank=True, default='QR Code sem título', max_length=200, verbose_name='Título'),
        ),
    ]
